import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.scss";

const playfair = Playfair({
  weight: '800',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={playfair.className}>{children}</body>
    </html>
  );
}
